server:
  port: 8081

#spring 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymovie?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: "0126"

#mybatis配置
mybatis:
  type-aliases-package: com.cjj.myapplication.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cjj.myapplication: debug


salt: xLJPk(MY!e)uOU%X