server:
  port: 8081

#spring 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mymovie?userUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: "0126"
  redis:
    database: 0
    host: localhost
    port: 6379


#mybatis配置
mybatis:
  type-aliases-package: com.cjj.myapplication.model
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.cjj.myapplication: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


salt: xLJPk(MY!e)uOU%X
